### PR TITLE
fix: dont show empty <li> tag on prouct detail actions

### PR DESCRIPTION
**Pull request by stroebjo**

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @stroebjo, Please sign the CLA.

**Comment by stroebjo** [comment]
I sent the signed CLA to you on Apr 26, 2017.

**Comment by kermie** [comment]
Hey @stroebjo,
we got this [picture](http://storage3.static.itmages.com/i/17/1124/h_1511516176_3878124_380f5e96cb.png). Please got to Details ;)
Cheers!

**Comment by Sieg** [comment]
Thanks you @stroebjo for the fix.

**Pull request merged**
