### PR TITLE
Modernize JavaScript

### PR DESCRIPTION
**Pull request by fpesch**
- Modernize JS using the [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html)
- Modernize theme.php

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @bpesch, so for this to work, we need higher versions of some components in package.json probably? or never version of node?

**Comment by bpesch** [comment]
Hi @Sieg,
it seems like the linter used by the project is outdated and it doesn't really like ES6.

Best regards.

**Comment by Sieg** [comment]
Hey @bpesch, could you please write the list of components that this build is green for you with?

**Comment by bpesch** [comment]
> Hey @bpesch, could you please write the list of components that this build is green for you with?

WDYM? The build should be green the linting / code analysis just isn't up to date

**Comment by bpesch** [comment]
didnt mean to close whoops

**Comment by Sieg** [comment]
Hello @bpesch, i have updated linter and some other components to higher versions and configured so its now understands es6.

There is still a problem that i could not solve by plugin update - with uglify:

```
vagrant@shop74:/var/www/oxideshop/source/Application/views/flow$ grunt
Running "copy:fonts" (copy) task
Copied 13 files

Running "jshint:theme" (jshint) task
>> 5 files lint free.

Running "less:theme" (less) task
>> 1 stylesheet created.

Running "less:vendor" (less) task
>> 1 stylesheet created.

Running "uglify:theme" (uglify) task
{ SyntaxError: Unexpected token: punc ())
    at JS_Parse_Error.get (eval at <anonymous> (/var/www/oxideshop/source/Application/views/flow/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (internal/util/inspect.js:818:16)
    at formatRaw (internal/util/inspect.js:617:14)
    at formatValue (internal/util/inspect.js:509:10)
    at inspect (internal/util/inspect.js:189:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:198:15)
    at Console.log (console.js:209:31)
    at /var/www/oxideshop/source/Application/views/flow/node_modules/grunt-contrib-uglify/tasks/uglify.js:141:17
    at Array.forEach (<anonymous>)
  message: 'Unexpected token: punc ())',
  filename: '../../../../build/js/main.js',
  line: 27,
  col: 4,
  pos: 1154 }
>> Uglifying source build/vendor/bootstrap/js/bootstrap.js,build/vendor/bootstrap-select/js/bootstrap-select.js,build/vendor/jquery-bootstrap-validation/js/jqBootstrapValidation.js,build/vendor/jquery-unveil/js/jquery.unveil.js,build/js/main.js failed.
Warning: Uglification failed.
Unexpected token: punc ()). 
Line 27 in build/vendor/bootstrap/js/bootstrap.js,build/vendor/bootstrap-select/js/bootstrap-select.js,build/vendor/jquery-bootstrap-validation/js/jqBootstrapValidation.js,build/vendor/jquery-unveil/js/jquery.unveil.js,build/js/main.js
 Use --force to continue.

Aborted due to warnings.


Execution Time (2020-10-21 16:41:00 UTC+2)
loading tasks  687ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 28%
copy:fonts      32ms  ▇▇ 1%
jshint:theme    93ms  ▇▇▇▇▇▇ 4%
less:theme      1.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 60%
less:vendor     57ms  ▇▇▇▇ 2%
uglify:theme   136ms  ▇▇▇▇▇▇▇▇▇ 5%
Total 2.5s

```

If you have more experience in this and know how to fix this, please let me know.

Use branch pr161 for checking my changes on the top of yours.

**Comment by Sieg** [comment]
Update: managed to make it working with harmony branch of uglify plugin

```
vagrant@shop74:/var/www/oxideshop/source/Application/views/flow$ npm install
npm WARN flow@1.0.0 No license field.

removed 19 packages and audited 406 packages in 2.545s

19 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
vagrant@shop74:/var/www/oxideshop/source/Application/views/flow$ grunt
Running "copy:fonts" (copy) task
Copied 13 files

Running "jshint:theme" (jshint) task
>> 5 files lint free.

Running "less:theme" (less) task
>> 1 stylesheet created.

Running "less:vendor" (less) task
>> 1 stylesheet created.

Running "uglify:theme" (uglify) task
>> 5 files created 189.2 kB → 92.07 kB

Running "uglify:vendor" (uglify) task
>> 7 files created 682.57 kB → 388.44 kB

Running "uglify:widgets" (uglify) task
>> 11 files created 40.2 kB → 11.44 kB

Done.


Execution Time (2020-10-21 17:08:36 UTC+2)
loading tasks   673ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 11%
jshint:theme     88ms  ▇▇▇ 1%
less:theme       1.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 22%
uglify:theme    913ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 14%
uglify:vendor    3.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 49%
uglify:widgets  100ms  ▇▇▇ 2%
Total 6.4s

```

**Comment by Sieg** [comment]
Hey @bpesch, everything would be great, but our CI is not prepared for this yet :D Looks like we will need more time on this PR to be in Open state :( Will let you know.

**Comment by Sieg** [comment]
Closing this as Flow is not supported for a while already. Dont hit me hard.

**Pull request closed without merging**
