### PR TITLE
new block for account order history

### PR DESCRIPTION
**Pull request by d3datadev**
Please merge this pull request, we need these blocks for our module

best regards
sk

### CODE REVIEW

**Comment by Sieg** [comment]
Hello, thank you for your pull request, please ensure you have signed the CLA. Github check shows that it is not signed. Thank you.

**Comment by Sieg** [comment]
Hello @d3datadev, please sign the CLA for current repository.

**Comment by ThomasDartsch** [comment]
now we signed the CLA.
any other open task?

**Comment by Sieg** [comment]
Thanks. Have just merged your pull request at https://github.com/OXID-eSales/flow_theme/commit/9cc8951e6700a7961c5bf349ccfb121b6f7a5c17

**Pull request closed without merging**
