### PR TITLE
bugfix for #6552

### PR DESCRIPTION
**Pull request by vanilla-thunder**
bug: https://bugs.oxid-esales.com/view.php?id=6552

problem origin:
photoswipe is initalized twice after loading variants with ajax. Sexond initialization overwrites cached initial class name for closed/hidden overlay with class name for open/visible overlay. Thats why overlay stays open but invisible.

fix found here:
https://github.com/dimsemenov/PhotoSwipe/issues/889#issuecomment-172364475

### CODE REVIEW

**Comment by TheKvist** [comment]
This is not a fix but a workaround, the original bug of initializing photoswipe twice still persists. The real problem of evaluating the script coming from ajax still persists and nobody seems to care... [This](https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/out/azure/src/js/widgets/oxarticlevariant.js#L60) is the line causing the bug, because this `WidgetsHandler` is always undefined, so the scripts get always evaluated.
Strangely enough, a file defining it exists, but is never included...

**Comment by sebbbbauer** [comment]
Hi @vanilla-thunder,

first of all: thanks for all your good work! Your pull request fixes the issue, but leaves the root cause untouched (as very well stated by @TheKvist). We should not leave the future "we" (every developer who will ask himself "Why is here a dead used if branch?") in struggle.

Thats why i would not merge the pull request as it is. Could you have a look at the root cause? One starting point, as mentioned by @TheKvist, is that the "azure/src/js/widgets/oxwidgetshandler.js" is not loaded near to this line:

https://github.com/OXID-eSales/flow_theme/blob/master/tpl/page/details/inc/productmain.tpl#L155

@TheKvist: maybe you would like to join and help @vanilla-thunder a bit? :)

Best regards,
Sebastian

**Comment by Sieg** [comment]
Hello @vanilla-thunder, @TheKvist, is this problem still viable for the latest eshop/flow theme versions? I cannot reproduce the issue. Will someone be interested in investigating and fixing the root cause if it is still broken?

**Comment by Sieg** [comment]
Closing the PR for now. Feel free to reopen/create a new one if the problem is still relevant and someone is willing to fix the root cause.

**Pull request closed without merging**
