### PR TITLE
Do not use sudo for npm

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @DanielRuf, i am not sure how you can install grunt globally without sudo, so i cannot take that one, but for installing of components in the directory, yes, you are right! Thanks for pointing (https://github.com/OXID-eSales/flow_theme/commit/4dbf47c0d284cd6cd9d3e1a566bcd61c959492c5).

**Comment by DanielRuf** [comment]
> Hello @DanielRuf, i am not sure how you can install grunt globally without sudo, its not working on our current VM implementation

It generally works. Even npm itself discourage using `sudo`.

Which VM? Users who read this have often a normal setup.

**Comment by DanielRuf** [comment]
We should not mention `sudo` in the readme.

**Comment by Sieg** [comment]
We want to ensure, everything works on our oxvm_eshop (https://github.com/OXID-eSales/oxvm_eshop), so sorry if you don't like it, but if it will not be mentioned, people who use it may have more questions, and otherwise, people who are using some "normal setup" as you say, will still have no problem by having that in readme, no?

**Comment by DanielRuf** [comment]
Well, `sudo npm i -g` causes often more problems than it solves, the npm itself warns about this.

But if you want to keep it as is, well then keep it (but I do not use your VM and avoid sudo for npm).

**Pull request closed without merging**
